# Generated by Django 3.2 on 2022-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Experience',
            field=models.TextField(help_text='<br>Type Experience in number.<br> Format: Year:YY, Months:MM, Days:DD '),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Billing_Cycle',
            field=models.TextField(),
        ),
    ]
