# Generated by Django 3.2 on 2022-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220404_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Billing_Cycle',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Received', 'Received')], default='0', max_length=100),
        ),
    ]
