# Generated by Django 3.2 on 2022-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_payment_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Billing_Cycle',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
