# Generated by Django 3.2 on 2022-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_billing_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.CharField(blank=True, help_text='<br>Use only capital INT', max_length=100)),
                ('Employee_name', models.CharField(blank=True, max_length=100)),
                ('Employee_Designation', models.CharField(blank=True, max_length=100)),
                ('Employee_Department', models.CharField(blank=True, max_length=100)),
                ('Member_type', models.CharField(choices=[('Done', 'Done'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=100)),
                ('Read', models.BooleanField(default=False)),
                ('Read_Write', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revoke_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.CharField(blank=True, help_text='<br>Use only capital INT', max_length=100)),
                ('Employee_name', models.CharField(blank=True, max_length=100)),
                ('Employee_Designation', models.CharField(blank=True, max_length=100)),
                ('Employee_Department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=100)),
            ],
        ),
    ]
