# Generated by Django 3.2 on 2022-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_request_permission_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_permission',
            name='Member_type',
            field=models.CharField(choices=[('New Access', 'New Access'), ('Modify Access', 'Modify Access')], default='Member type', max_length=100),
        ),
        migrations.AlterField(
            model_name='request_permission',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Task pending', 'Task pending')], default='Task pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='revoke_permission',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Task pending', 'Task pending')], default='Task pending', max_length=100),
        ),
    ]
