# Generated by Django 3.2 on 2022-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220411_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Experience',
            field=models.TextField(help_text='<br>Type Experience in number.<br> Format: Year:YY, Months:MM '),
        ),
    ]
