# Generated by Django 3.2 on 2022-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220412_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Certified_Skill',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Experience',
            field=models.TextField(blank=True, default=None, help_text='<br>Type Experience in number.<br> Format: Year:YY, Months:MM '),
        ),
        migrations.AlterField(
            model_name='employees',
            name='KRA',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Skill',
            field=models.TextField(blank=True, default=None),
        ),
    ]
