# Generated by Django 3.2 on 2022-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_employees_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Compliance_document',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='PO_Terms_and_Conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Payment_Cycle',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly'), ('Partially', 'Partially')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='SOW',
            field=models.TextField(blank=True),
        ),
    ]
