# Generated by Django 3.2 on 2022-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220412_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Experience',
            field=models.CharField(blank=True, default=None, help_text='<br>Type Experience in number.<br> Format: Year:YY, Months:MM ', max_length=100),
        ),
    ]
