# Generated by Django 3.2 on 2022-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_employees_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Partial_Cycle',
            field=models.CharField(blank=True, default='0', help_text='ONLY TYPE IN WHEN PAYMENT CYCLE IS PARTIALLY or else leave it blank', max_length=100),
        ),
    ]
