# Generated by Django 3.2 on 2022-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment_partial_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Partial_Cycle',
            field=models.CharField(blank=True, default='None', help_text='ONLY TYPE IN WHEN PAYMENT CYCLE IS PARTIALLY or else leave it blank', max_length=100),
        ),
    ]
