# Generated by Django 3.2 on 2022-04-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_payment_partial_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Status',
            field=models.CharField(choices=[('Invoice Not Submitted', 'Invoice Not Submitted'), ('Payment Pending', 'Payment Pending'), ('Invoice Submitted', 'Invoice Submitted'), ('Payment Received', 'Payment Received')], default='0', max_length=100),
        ),
    ]
